workflows:
  build-deploy-beta:
    name: Build and Deploy to Beta
    max_build_duration: 60
    environment:
      android_signing:
        - scaling_broccoli
      vars:
        PACKAGE_NAME: "org.godotengine.gamejammerge"
        GODOT_VERSION: 4.0.3
        GODOT_EXEC_URL: https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_macos.universal.zip
        GODOT_TEMPLATES_URL: https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
        GODOT_TEMPLATES_DIR: "/Users/builder/Library/Application\ Support/Godot/export_templates"
        GODOT_EXEC: "Godot.app/Contents/MacOS/Godot"
        EXPORT_TYPE: "Android"
    scripts:
      - name:  Download Godot
        script: |
          pwd && ls
          echo ${GODOT_EXEC_URL}
          curl -LO ${GODOT_EXEC_URL} && unzip Godot_v${GODOT_VERSION}-stable_macos.universal.zip
          pwd && ls
      - name:  Download Godot templates
        script: |
          pwd && ls
          echo ${GODOT_TEMPLATES_URL}
          curl -LO ${GODOT_TEMPLATES_URL} && unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          pwd && ls
      - name:  Setup templates
        script: |
          pwd && ls
          echo ${GODOT_TEMPLATES_DIR}
          mkdir -p "${GODOT_TEMPLATES_DIR}" && mv templates "${GODOT_TEMPLATES_DIR}/${GODOT_VERSION}.stable"
          pwd && ls
      - name: Create build directory
        script: |
          mkdir -p exports/android/
      - name: Create export presets
        script: |
          python3 scripts/exports/create-export-preset.py \
            --path $CM_KEYSTORE_PATH \
            --alias $CM_KEY_ALIAS \
            --password $CM_KEY_PASSWORD
      - name: Import resources
        script: |
          # https://github.com/godotengine/godot-proposals/issues/1362#issuecomment-1379140108
          echo "Workaround to import assets"
      - name: Build Android app
        script: |
          mkdir -p ../exports/android
          cd mobile-game/
          ${GODOT_EXEC} --export-release "Android" ../exports/android/scaling-broccoli.aab --headless
          cd ../
    artifacts:
      - exports/**/*.aab
      
      