workflows:
  godot-ios-workflow:
      name: Godot iOS Workflow
      max_build_duration: 60
      environment:
        groups:
          - godot
        vars:
          GODOT_VERSION: 4.0.2
          GODOT_EXEC_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_osx.universal.zip
          GODOT_TEMPLATES_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          GODOT_TEMPLATES_DIR: "/Users/builder/Library/Application Support/Godot/templates"
          GODOT_EXEC: Godot.app/Contents/MacOS/Godot
          EXPORT_TYPE: iOS Production
          ARTIFACT: app.zip
      scripts:
        - name: Download Godot engine
          script: |
                        curl -o ./godot.zip ${GODOT_EXEC_URL} && unzip ./godot.zip
        - name: Download Godot templates
          script: |
                        curl -o ./godot-templates.zip ${GODOT_TEMPLATES_URL} && unzip ./godot-templates.zip
        - name: Setup templates
          script: |
                        mkdir -p "${GODOT_TEMPLATES_DIR}" && mv templates "${GODOT_TEMPLATES_DIR}/${GODOT_VERSION}.stable"
        - name: Prepare build directory
          script: mkdir build/
        - name: Export project
          script: ${GODOT_EXEC} --path mobile-game/ --no-window --export "${EXPORT_TYPE}" build/${ARTIFACT}
      artifacts:
        - build/*.zip
