workflows:
  build-deploy-beta:
    name: Build and Deploy to Beta
    max_build_duration: 60
    environment:
      android_signing:
        - scaling_broccoli
      vars:
        PACKAGE_NAME: "org.godotengine.gamejammerge"
        EXPORT_TYPE: "Android"
    scripts:
      - name:  Install godot latest
        script: |
          brew install --cask godot
      - name: Create build directory
        script: |
          mkdir -p exports/android/
      - name: Create export presets
        script: |
          python3 scripts/exports/create-export-preset.py \
            --path $CM_KEYSTORE_PATH \
            --alias $CM_KEY_ALIAS \
            --password $CM_KEY_PASSWORD
      - name: Import resources
        script: |
          cd mobile-game/
          godot --headless --editor --quite
          cd ../
      - name: Build Android app
        script: |
          mkdir -p ../exports/android
          cd mobile-game/
          godot --export-release "Android" ../exports/android/scaling-broccoli.aab --headless
          cd ../
    artifacts:
      - exports/**/*.aab
      
      